version: "2.1"
services:
  courses-ms:
    build: .
    ports:
      - "3000:3000"


  courses-db:
    image: mysql:5.7

    environment:
      MYSQL_ROOT_PASSWORD: 123
      MYSQL_DATABASE: courses-db
      MYSQL_USER: sa
      MYSQL_PASSWORD: 123
    ports:
      - "3306:3306"
